name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce?
      description: |
        Please provide a minimal reproducible example (MRE).
        This helps us verify the bug and fix it faster.
      placeholder: |
        1. Run '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: AKQuant Version
      description: What version of our software are you running?
      placeholder: e.g., 0.1.15
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
