# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing
import numpy as np

import akquant

class AssetType:
    Stock: typing.ClassVar["AssetType"]
    Futures: typing.ClassVar["AssetType"]
    def __init__(self, *args: typing.Any, **kwargs: typing.Any) -> None: ...

class OrderSide:
    Buy: typing.ClassVar["OrderSide"]
    Sell: typing.ClassVar["OrderSide"]
    def __init__(self, *args: typing.Any, **kwargs: typing.Any) -> None: ...

class OrderType:
    Market: typing.ClassVar["OrderType"]
    Limit: typing.ClassVar["OrderType"]
    def __init__(self, *args: typing.Any, **kwargs: typing.Any) -> None: ...

class OrderStatus:
    New: typing.ClassVar["OrderStatus"]
    Submitted: typing.ClassVar["OrderStatus"]
    Filled: typing.ClassVar["OrderStatus"]
    Cancelled: typing.ClassVar["OrderStatus"]
    Rejected: typing.ClassVar["OrderStatus"]
    Expired: typing.ClassVar["OrderStatus"]
    def __init__(self, *args: typing.Any, **kwargs: typing.Any) -> None: ...

class TimeInForce:
    GTC: typing.ClassVar["TimeInForce"]
    IOC: typing.ClassVar["TimeInForce"]
    FOK: typing.ClassVar["TimeInForce"]
    Day: typing.ClassVar["TimeInForce"]
    def __init__(self, *args: typing.Any, **kwargs: typing.Any) -> None: ...

class ExecutionMode:
    CurrentClose: typing.ClassVar["ExecutionMode"]
    NextOpen: typing.ClassVar["ExecutionMode"]
    def __init__(self, *args: typing.Any, **kwargs: typing.Any) -> None: ...

class TradingSession:
    PreOpen: typing.ClassVar["TradingSession"]
    Continuous: typing.ClassVar["TradingSession"]
    CallAuction: typing.ClassVar["TradingSession"]
    Break: typing.ClassVar["TradingSession"]
    Closed: typing.ClassVar["TradingSession"]
    PostClose: typing.ClassVar["TradingSession"]
    def __init__(self, *args: typing.Any, **kwargs: typing.Any) -> None: ...

class BacktestResult:
    r"""回测结果."""

    equity_curve: list[tuple[int, float]]
    metrics: PerformanceMetrics
    trade_metrics: TradePnL
    trades: list[ClosedTrade]
    daily_positions: list[tuple[int, dict[str, float]]]

class ClosedTrade:
    r"""
    平仓交易记录.

    :ivar symbol: 标的代码
    :ivar entry_time: 开仓时间戳
    :ivar exit_time: 平仓时间戳
    :ivar entry_price: 开仓价格
    :ivar exit_price: 平仓价格
    :ivar quantity: 交易数量
    :ivar direction: 交易方向 ("Long" or "Short")
    :ivar pnl: 毛利 (Gross PnL)，不包含佣金 (aligned with Backtrader)
    :ivar net_pnl: 净利 (Net PnL)，包含佣金 (pnl - commission)
    :ivar return_pct: 收益率
    :ivar commission: 交易佣金
    :ivar duration_bars: 持仓周期数
    """

    symbol: str
    entry_time: int
    exit_time: int
    entry_price: float
    exit_price: float
    quantity: float
    direction: str
    pnl: float
    net_pnl: float
    return_pct: float
    commission: float
    duration_bars: int

class Bar:
    r"""
    K线数据结构.

    :ivar timestamp: Unix 时间戳 (纳秒)
    :ivar open: 开盘价
    :ivar high: 最高价
    :ivar low: 最低价
    :ivar close: 收盘价
    :ivar volume: 成交量
    :ivar symbol: 标的代码
    """

    timestamp: int
    symbol: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    def __new__(
        cls,
        timestamp: typing.Any,
        open: typing.Any,
        high: typing.Any,
        low: typing.Any,
        close: typing.Any,
        volume: typing.Any,
        symbol: str,
    ) -> Bar: ...
    def set_open(self, value: typing.Any) -> None: ...
    def set_high(self, value: typing.Any) -> None: ...
    def set_low(self, value: typing.Any) -> None: ...
    def set_close(self, value: typing.Any) -> None: ...
    def set_volume(self, value: typing.Any) -> None: ...
    def __repr__(self) -> str: ...

class DataFeed:
    def __init__(self) -> None: ...
    def add_bar(self, bar: Bar) -> None: ...
    def add_bars(self, bars: typing.Sequence[Bar]) -> None: ...
    def add_arrays(
        self,
        timestamps: typing.Sequence[int],
        opens: typing.Sequence[float],
        highs: typing.Sequence[float],
        lows: typing.Sequence[float],
        closes: typing.Sequence[float],
        volumes: typing.Sequence[float],
        symbol: typing.Optional[str] = None,
        symbols: typing.Optional[typing.Sequence[str]] = None,
        extra: typing.Optional[typing.Dict[str, typing.Sequence[float]]] = None,
    ) -> None: ...
    def sort(self) -> None: ...
    def add_tick(self, tick: Tick) -> None: ...

class Engine:
    r"""
    主回测引擎.

    :ivar feed: 数据源
    :ivar portfolio: 投资组合
    :ivar orders: 订单列表
    :ivar trades: 成交列表
    """

    portfolio: Portfolio
    risk_manager: RiskManager
    orders: list[Order]
    trades: list[Trade]
    def __new__(
        cls,
    ) -> Engine: ...
    def set_execution_mode(self, mode: akquant.ExecutionMode) -> None:
        r"""
        设置撮合模式.

        :param mode: 撮合模式 (ExecutionMode.CurrentClose 或 ExecutionMode.NextOpen)
        :type mode: ExecutionMode
        """
        ...

    def set_timezone(self, offset: int) -> None: ...
    def set_timezone_name(self, tz_name: str) -> None:
        r"""
        通过时区名称设置引擎时区.

        :param tz_name: 时区名称，例如 "Asia/Shanghai", "UTC", "US/Eastern"
        """
        ...
    def use_simple_market(self, commission_rate: float) -> None:
        r"""
        启用 SimpleMarket (7x24小时, T+0, 无税, 简单佣金).

        :param commission_rate: 佣金率
        """
        ...

    def use_china_market(self) -> None:
        r"""启用 ChinaMarket (支持 T+1/T+0, 印花税, 过户费, 交易时段等)."""
        ...

    def use_china_futures_market(self) -> None:
        r"""
        启用中国期货市场默认配置.

        - 切换到 ChinaMarket
        - 设置 T+0
        - 保持当前交易时段配置 (需手动设置 set_market_sessions 以匹配特定品种).
        """
        ...

    def set_t_plus_one(self, enabled: bool) -> None:
        r"""
        启用/禁用 T+1 交易规则 (仅针对 ChinaMarket).

        :param enabled: 是否启用 T+1
        :type enabled: bool
        """
        ...

    def set_force_session_continuous(self, enabled: bool) -> None: ...
    def set_stock_fee_rules(
        self,
        commission_rate: float,
        stamp_tax: float,
        transfer_fee: float,
        min_commission: float,
    ) -> None: ...
    def set_future_fee_rules(self, commission_rate: float) -> None: ...
    def set_fund_fee_rules(
        self,
        commission_rate: float,
        transfer_fee: float,
        min_commission: float,
    ) -> None: ...
    def set_option_fee_rules(self, commission_per_contract: float) -> None: ...
    def set_slippage(self, type: str, value: float) -> None:
        r"""
        设置滑点模型.

        :param type: 滑点类型 ("fixed" 或 "percent")
        :param value: 滑点值 (固定金额 或 百分比如 0.001)
        """
        ...
    def set_volume_limit(self, limit: float) -> None:
        r"""
        设置成交量限制.

        :param limit: 限制比例 (0.0-1.0), 0.0 为不限制
        """
        ...
    def set_market_sessions(
        self, sessions: typing.Sequence[tuple[str, str, akquant.TradingSession]]
    ) -> None: ...
    def add_instrument(self, instrument: Instrument) -> None:
        r"""
        添加交易标的.

        :param instrument: 交易标的对象
        :type instrument: Instrument
        """
        ...

    def set_cash(self, cash: float) -> None:
        r"""
        设置初始资金.

        :param cash: 初始资金数额
        :type cash: float
        """
        ...

    def add_data(self, feed: DataFeed) -> None:
        r"""
        添加数据源.

        :param feed: 数据源对象
        :type feed: DataFeed
        """
        ...

    def add_bars(self, bars: typing.Sequence[Bar]) -> None:
        r"""
        批量添加 K 线数据.

        :param bars: K 线列表
        """
        ...

    def run(self, strategy: typing.Any, show_progress: bool = False) -> str:
        r"""
        运行回测.

        :param strategy: 策略对象
        :type strategy: object
        :param show_progress: 是否显示进度条
        :return: 回测结果摘要
        :rtype: str
        """
        ...

    def get_results(self) -> BacktestResult:
        r"""
        获取回测结果.

        :return: BacktestResult
        """
        ...

    def create_context(
        self, active_orders: typing.Sequence[Order]
    ) -> StrategyContext: ...

class Instrument:
    r"""
    交易标的.

    :ivar symbol: 代码
    :ivar asset_type: 资产类型
    :ivar multiplier: 合约乘数
    :ivar margin_ratio: 保证金比率
    :ivar tick_size: 最小变动价位
    """

    symbol: str
    asset_type: akquant.AssetType
    multiplier: float
    margin_ratio: float
    tick_size: float
    def __new__(
        cls,
        symbol: str,
        asset_type: akquant.AssetType,
        multiplier: typing.Any,
        margin_ratio: typing.Any,
        tick_size: typing.Any,
        option_type: typing.Optional[str] = None,
        strike_price: typing.Optional[float] = None,
        expiry_date: typing.Optional[typing.Any] = None,
        lot_size: typing.Optional[float] = None,
    ) -> Instrument: ...

class Order:
    r"""
    订单.

    :ivar id: 订单ID
    :ivar symbol: 标的代码
    :ivar side: 交易方向
    :ivar order_type: 订单类型
    :ivar quantity: 数量
    :ivar price: 价格 (限价单有效)
    :ivar time_in_force: 订单有效期
    :ivar trigger_price: 触发价格 (止损/止盈单)
    :ivar status: 订单状态
    :ivar filled_quantity: 已成交数量
    :ivar average_filled_price: 成交均价
    """

    id: str
    symbol: str
    side: akquant.OrderSide
    order_type: akquant.OrderType
    time_in_force: akquant.TimeInForce
    status: akquant.OrderStatus
    quantity: float
    price: typing.Optional[float]
    trigger_price: typing.Optional[float]
    filled_quantity: float
    average_filled_price: typing.Optional[float]
    def __new__(
        cls,
        id: str,
        symbol: str,
        side: OrderSide,
        order_type: OrderType,
        quantity: float,
        price: typing.Optional[float] = None,
        time_in_force: TimeInForce = ...,
        trigger_price: typing.Optional[float] = None,
        status: OrderStatus = ...,
        filled_quantity: float = 0.0,
        average_filled_price: typing.Optional[float] = None,
    ) -> Order: ...
    def __repr__(self) -> str: ...

class PerformanceMetrics:
    r"""绩效指标."""

    total_return: float
    annualized_return: float
    max_drawdown: float
    max_drawdown_pct: float
    sharpe_ratio: float
    sortino_ratio: float
    volatility: float
    ulcer_index: float
    upi: float
    equity_r2: float
    std_error: float
    win_rate: float
    initial_market_value: float
    end_market_value: float
    total_return_pct: float

class Portfolio:
    r"""
    投资组合管理.

    :ivar cash: 当前现金余额
    :ivar positions: 当前持仓 (symbol -> quantity)
    :ivar available_positions: 可用持仓 (symbol -> quantity)
    """

    cash: float
    positions: dict[str, float]
    available_positions: dict[str, float]
    def __new__(cls, cash: typing.Any) -> Portfolio: ...
    def get_position(self, symbol: str) -> float: ...
    def get_available_position(self, symbol: str) -> float: ...
    def __repr__(self) -> str: ...

class StrategyContext:
    r"""
    策略上下文.

    :ivar orders: 订单列表 (内部使用)
    :ivar cash: 当前现金
    :ivar positions: 当前持仓
    :ivar available_positions: 可用持仓
    :ivar session: 当前交易时段
    """

    orders: list[Order]
    active_orders: list[Order]
    session: akquant.TradingSession
    cash: float
    positions: dict[str, float]
    available_positions: dict[str, float]
    def __new__(
        cls,
        cash: typing.Any,
        positions: typing.Mapping[str, float],
        available_positions: typing.Mapping[str, float],
        session: typing.Optional[akquant.TradingSession],
        active_orders: typing.Optional[typing.Sequence[Order]],
    ) -> StrategyContext: ...
    def schedule(self, timestamp: int, payload: str) -> None:
        r"""
        注册定时器.

        :param timestamp: 触发时间戳 (秒)
        :param payload: 携带的数据 (如回调函数名)
        """
        ...

    def buy(
        self,
        symbol: str,
        quantity: float,
        price: typing.Optional[float] = ...,
        time_in_force: typing.Optional[akquant.TimeInForce] = ...,
        trigger_price: typing.Optional[float] = ...,
    ) -> None: ...
    def sell(
        self,
        symbol: str,
        quantity: float,
        price: typing.Optional[float] = ...,
        time_in_force: typing.Optional[akquant.TimeInForce] = ...,
        trigger_price: typing.Optional[float] = ...,
    ) -> None: ...
    def get_position(self, symbol: str) -> float: ...
    def get_available_position(self, symbol: str) -> float: ...
    def cancel_order(self, order_id: str) -> None:
        """
        取消订单.

        :param order_id: 订单 ID
        """
        ...
    def history(
        self, symbol: str, field: str, count: int
    ) -> typing.Optional[np.ndarray]: ...

class Tick:
    r"""
    Tick 数据结构.

    :ivar timestamp: Unix 时间戳 (纳秒)
    :ivar price: 最新价
    :ivar volume: 成交量
    :ivar symbol: 标的代码
    """

    timestamp: int
    symbol: str
    price: float
    volume: float
    def __new__(
        cls, timestamp: typing.Any, price: typing.Any, volume: typing.Any, symbol: str
    ) -> Tick: ...
    def set_price(self, value: typing.Any) -> None: ...
    def set_volume(self, value: typing.Any) -> None: ...
    def __repr__(self) -> str: ...

class Trade:
    r"""
    成交记录.

    :ivar id: 成交ID
    :ivar order_id: 订单ID
    :ivar symbol: 标的代码
    :ivar side: 交易方向
    :ivar quantity: 成交数量
    :ivar price: 成交价格
    :ivar commission: 手续费
    :ivar timestamp: Unix 时间戳
    """

    id: str
    order_id: str
    symbol: str
    side: akquant.OrderSide
    timestamp: int
    bar_index: int
    quantity: float
    price: float
    commission: float
    def __new__(
        cls,
        id: str,
        order_id: str,
        symbol: str,
        side: akquant.OrderSide,
        quantity: typing.Any,
        price: typing.Any,
        commission: typing.Any,
        timestamp: int,
        bar_index: int,
    ) -> Trade: ...
    def __repr__(self) -> str: ...

class TradeAnalyzer: ...

class TradePnL:
    r"""交易盈亏统计 (FIFO)."""

    gross_pnl: float
    net_pnl: float
    total_commission: float
    total_closed_trades: int
    won_count: int
    lost_count: int
    won_pnl: float
    lost_pnl: float
    win_rate: float

    loss_rate: float
    unrealized_pnl: float
    avg_pnl: float
    avg_return_pct: float
    avg_trade_bars: float
    avg_profit: float
    avg_profit_pct: float
    avg_winning_trade_bars: float
    avg_loss: float
    avg_loss_pct: float
    avg_losing_trade_bars: float
    largest_win: float
    largest_win_pct: float
    largest_win_bars: float
    largest_loss: float
    largest_loss_pct: float
    largest_loss_bars: float
    max_wins: int
    max_losses: int
    profit_factor: float
    total_profit: float
    total_loss: float

def from_arrays(
    timestamps: typing.Sequence[int],
    opens: typing.Sequence[float],
    highs: typing.Sequence[float],
    lows: typing.Sequence[float],
    closes: typing.Sequence[float],
    volumes: typing.Sequence[float],
    symbol: typing.Optional[str],
    symbols: typing.Optional[typing.Sequence[str]],
) -> list[Bar]:
    r"""从数组批量创建 Bar 列表 (Python 优化用)."""
    ...

class SMA:
    r"""
    Simple Moving Average (SMA).

    Calculates the arithmetic mean of the last `period` data points.
    """

    def __init__(self, period: int) -> None:
        r"""
        Create a new SMA indicator.

        :param period: The window size for the moving average.
        """
        ...
    def update(self, value: float) -> typing.Optional[float]:
        r"""
        Update the indicator with a new value.

        :param value: The new data point.
        :return: The current SMA value if enough data points have been collected, else None.
        """
        ...
    @property
    def value(self) -> typing.Optional[float]: ...
    @property
    def is_ready(self) -> bool: ...

class RiskConfig:
    max_order_size: typing.Optional[float]
    max_order_value: typing.Optional[float]
    max_position_size: typing.Optional[float]
    restricted_list: list[str]
    active: bool
    def __init__(self) -> None: ...

class RiskManager:
    config: RiskConfig
    def __init__(self) -> None: ...
    def check(self, order: Order, portfolio: Portfolio) -> typing.Optional[str]: ...
