# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

import numpy
import numpy.typing

import akquant

class AssetType:
    Stock: "AssetType"
    Future: "AssetType"
    Option: "AssetType"
    Fund: "AssetType"
    Crypto: "AssetType"
    Forex: "AssetType"
    Index: "AssetType"
    Bond: "AssetType"

class ExecutionMode:
    CurrentClose: "ExecutionMode"
    NextOpen: "ExecutionMode"

class OptionType:
    Call: "OptionType"
    Put: "OptionType"

class OrderSide:
    Buy: "OrderSide"
    Sell: "OrderSide"

class OrderStatus:
    New: "OrderStatus"
    Submitted: "OrderStatus"
    PartiallyFilled: "OrderStatus"
    Filled: "OrderStatus"
    Canceled: "OrderStatus"
    Rejected: "OrderStatus"
    Expired: "OrderStatus"

class OrderType:
    Market: "OrderType"
    Limit: "OrderType"
    Stop: "OrderType"
    StopLimit: "OrderType"

class TimeInForce:
    GTC: "TimeInForce"
    Day: "TimeInForce"
    IOC: "TimeInForce"
    FOK: "TimeInForce"
    GTD: "TimeInForce"

class TradingSession:
    PreMarket: "TradingSession"
    Regular: "TradingSession"
    PostMarket: "TradingSession"

class BacktestResult:
    r"""回测结果."""

    equity_curve: list[tuple[int, float]]
    metrics: PerformanceMetrics
    trade_metrics: TradePnL
    trades: list[ClosedTrade]
    daily_positions: list[tuple[int, dict[str, float]]]

class Bar:
    r"""
    K线数据结构.

    :ivar timestamp: Unix 时间戳 (纳秒)
    :ivar open: 开盘价
    :ivar high: 最高价
    :ivar low: 最低价
    :ivar close: 收盘价
    :ivar volume: 成交量
    :ivar symbol: 标的代码
    """

    timestamp: int
    symbol: str
    extra: dict[str, float]
    open: float
    high: float
    low: float
    close: float
    volume: float
    def __new__(
        cls,
        timestamp: int,
        open: float,
        high: float,
        low: float,
        close: float,
        volume: float,
        symbol: str,
        extra: typing.Optional[dict[str, float]] = None,
    ) -> "Bar": ...
    def set_open(self, value: float) -> None: ...
    def set_high(self, value: float) -> None: ...
    def set_low(self, value: float) -> None: ...
    def set_close(self, value: float) -> None: ...
    def set_volume(self, value: float) -> None: ...
    def __repr__(self) -> str: ...

class ClosedTrade:
    r"""平仓交易记录."""

    symbol: str
    entry_time: int
    exit_time: int
    entry_price: float
    exit_price: float
    quantity: float
    direction: str
    pnl: float
    net_pnl: float
    return_pct: float
    commission: float
    duration_bars: int

class DataFeed:
    def __new__(cls) -> "DataFeed": ...
    def add_bars(self, bars: typing.Sequence[Bar]) -> None: ...
    def sort(self) -> None: ...

class Engine:
    r"""
    主回测引擎.

    :ivar feed: 数据源
    :ivar portfolio: 投资组合
    :ivar orders: 订单列表
    :ivar trades: 成交列表
    """

    portfolio: Portfolio
    orders: list[Order]
    trades: list[Trade]
    risk_manager: RiskManager
    def __new__(cls) -> "Engine": ...
    def set_history_depth(self, depth: int) -> None: ...
    def set_timezone(self, offset: int) -> None: ...
    def set_execution_mode(self, mode: ExecutionMode) -> None: ...
    def use_simple_market(self, commission_rate: float) -> None: ...
    def use_china_market(self) -> None: ...
    def use_china_futures_market(self) -> None: ...
    def set_t_plus_one(self, enabled: bool) -> None: ...
    def set_force_session_continuous(self, enabled: bool) -> None: ...
    def set_stock_fee_rules(
        self,
        commission_rate: float,
        stamp_tax: float,
        transfer_fee: float,
        min_commission: float,
    ) -> None: ...
    def set_future_fee_rules(self, commission_rate: float) -> None: ...
    def set_fund_fee_rules(
        self, commission_rate: float, transfer_fee: float, min_commission: float
    ) -> None: ...
    def set_option_fee_rules(self, commission_per_contract: float) -> None: ...
    def set_slippage(self, type_: str, value: float) -> None: ...
    def set_volume_limit(self, limit: float) -> None: ...
    def set_market_sessions(
        self, sessions: typing.Sequence[tuple[str, str, TradingSession]]
    ) -> None: ...
    def add_instrument(self, instrument: Instrument) -> None: ...
    def set_cash(self, cash: float) -> None: ...
    def add_data(self, feed: DataFeed) -> None: ...
    def add_bars(self, bars: typing.Sequence[Bar]) -> None: ...
    def run(self, strategy: typing.Any, show_progress: bool) -> str: ...
    def get_results(self) -> BacktestResult: ...
    def create_context(
        self, active_orders: typing.Sequence[Order]
    ) -> StrategyContext: ...

class Instrument:
    r"""
    交易标的.

    :ivar symbol: 代码
    :ivar asset_type: 资产类型
    :ivar multiplier: 合约乘数
    :ivar margin_ratio: 保证金比率
    :ivar tick_size: 最小变动价位
    """

    symbol: str
    asset_type: AssetType
    multiplier: float
    margin_ratio: float
    tick_size: float
    def __new__(
        cls,
        symbol: str,
        asset_type: AssetType,
        multiplier: float,
        margin_ratio: float,
        tick_size: float,
        option_type: typing.Optional[OptionType] = None,
        strike_price: typing.Optional[float] = None,
        expiry_date: typing.Optional[int] = None,
        lot_size: typing.Optional[float] = None,
    ) -> "Instrument": ...

class Order:
    r"""
    订单.

    :ivar id: 订单ID
    :ivar symbol: 标的代码
    :ivar side: 交易方向
    :ivar order_type: 订单类型
    :ivar quantity: 数量
    :ivar price: 价格 (限价单有效)
    :ivar time_in_force: 订单有效期
    :ivar trigger_price: 触发价格 (止损/止盈单)
    :ivar status: 订单状态
    :ivar filled_quantity: 已成交数量
    :ivar average_filled_price: 成交均价
    """

    id: str
    symbol: str
    side: OrderSide
    order_type: OrderType
    time_in_force: TimeInForce
    status: OrderStatus
    quantity: float
    price: typing.Optional[float]
    trigger_price: typing.Optional[float]
    filled_quantity: float
    average_filled_price: typing.Optional[float]
    def __new__(
        cls,
        id: str,
        symbol: str,
        side: OrderSide,
        order_type: OrderType,
        quantity: float,
        price: typing.Optional[float] = None,
        time_in_force: TimeInForce = ...,
        trigger_price: typing.Optional[float] = None,
    ) -> "Order": ...
    def __repr__(self) -> str: ...

class PerformanceMetrics:
    r"""绩效指标."""

    total_return: float
    annualized_return: float
    max_drawdown: float
    max_drawdown_pct: float
    sharpe_ratio: float
    sortino_ratio: float
    volatility: float
    ulcer_index: float
    upi: float
    equity_r2: float
    std_error: float
    win_rate: float
    initial_market_value: float
    end_market_value: float
    total_return_pct: float

class Portfolio:
    r"""
    投资组合管理.

    :ivar cash: 当前现金余额
    :ivar positions: 当前持仓 (symbol -> quantity)
    :ivar available_positions: 可用持仓 (symbol -> quantity)
    """

    cash: float
    positions: dict[str, float]
    available_positions: dict[str, float]
    def __new__(cls, cash: float) -> "Portfolio": ...
    def get_position(self, symbol: str) -> float: ...
    def get_available_position(self, symbol: str) -> float: ...

class RiskConfig:
    r"""
    风控配置.

    :ivar max_order_size: 单笔最大下单数量
    :ivar max_order_value: 单笔最大下单金额
    :ivar max_position_size: 最大持仓数量 (绝对值)
    :ivar restricted_list: 限制交易标的列表
    :ivar active: 是否启用风控
    """

    max_order_size: float
    max_order_value: float
    max_position_size: float
    restricted_list: list[str]
    active: bool

class RiskManager:
    r"""
    风控管理器.

    :ivar config: 风控配置
    """

    config: RiskConfig
    def __new__(cls) -> "RiskManager": ...
    def check(self, order: Order, portfolio: Portfolio) -> typing.Optional[str]: ...

class SMA:
    value: typing.Optional[float]
    is_ready: bool
    def __new__(cls, period: int) -> "SMA": ...
    def update(self, value: float) -> typing.Optional[float]: ...

class StrategyContext:
    r"""
    策略上下文.

    :ivar orders: 订单列表 (内部使用)
    :ivar cash: 当前现金
    :ivar positions: 当前持仓
    :ivar available_positions: 可用持仓
    :ivar session: 当前交易时段
    """

    orders: list[Order]
    canceled_order_ids: list[str]
    active_orders: list[Order]
    session: TradingSession
    last_closed_trade: typing.Optional[ClosedTrade]
    closed_trades: list[ClosedTrade]
    cash: float
    positions: dict[str, float]
    available_positions: dict[str, float]
    def __new__(
        cls,
        cash: float,
        positions: typing.Mapping[str, float],
        available_positions: typing.Mapping[str, float],
        session: typing.Optional[TradingSession],
        active_orders: typing.Optional[typing.Sequence[Order]],
        closed_trades: typing.Optional[typing.Sequence[ClosedTrade]],
    ) -> "StrategyContext": ...
    def history(
        self, symbol: str, field: str, count: int
    ) -> typing.Optional[numpy.typing.NDArray[numpy.float64]]: ...
    def schedule(self, timestamp: int, payload: str) -> None: ...
    def cancel_order(self, order_id: str) -> None: ...
    def buy(
        self,
        symbol: str,
        quantity: float,
        price: typing.Optional[float] = None,
        time_in_force: typing.Optional[TimeInForce] = None,
        trigger_price: typing.Optional[float] = None,
    ) -> None: ...
    def sell(
        self,
        symbol: str,
        quantity: float,
        price: typing.Optional[float] = None,
        time_in_force: typing.Optional[TimeInForce] = None,
        trigger_price: typing.Optional[float] = None,
    ) -> None: ...
    def get_position(self, symbol: str) -> float: ...
    def get_available_position(self, symbol: str) -> float: ...

class Tick:
    r"""
    Tick 数据结构.

    :ivar timestamp: Unix 时间戳 (纳秒)
    :ivar price: 最新价
    :ivar volume: 成交量
    :ivar symbol: 标的代码
    """

    timestamp: int
    symbol: str
    price: float
    volume: float
    def __new__(
        cls, timestamp: int, price: float, volume: float, symbol: str
    ) -> "Tick": ...
    def set_price(self, value: float) -> None: ...
    def set_volume(self, value: float) -> None: ...
    def __repr__(self) -> str: ...

class Trade:
    r"""
    成交记录.

    :ivar id: 成交ID
    :ivar order_id: 订单ID
    :ivar symbol: 标的代码
    :ivar side: 交易方向
    :ivar quantity: 成交数量
    :ivar price: 成交价格
    :ivar commission: 手续费
    :ivar timestamp: Unix 时间戳 (纳秒)
    """

    id: str
    order_id: str
    symbol: str
    side: OrderSide
    timestamp: int
    bar_index: int
    quantity: float
    price: float
    commission: float
    def __new__(
        cls,
        id: str,
        order_id: str,
        symbol: str,
        side: OrderSide,
        quantity: float,
        price: float,
        commission: float,
        timestamp: int,
        bar_index: int,
    ) -> "Trade": ...
    def __repr__(self) -> str: ...

class TradePnL:
    r"""交易盈亏统计 (FIFO)."""

    gross_pnl: float
    net_pnl: float
    total_commission: float
    total_closed_trades: int
    won_count: int
    lost_count: int
    won_pnl: float
    lost_pnl: float
    win_rate: float
    loss_rate: float
    unrealized_pnl: float
    avg_pnl: float
    avg_return_pct: float
    avg_trade_bars: float
    avg_profit: float
    avg_profit_pct: float
    avg_winning_trade_bars: float
    avg_loss: float
    avg_loss_pct: float
    avg_losing_trade_bars: float
    largest_win: float
    largest_win_pct: float
    largest_win_bars: float
    largest_loss: float
    largest_loss_pct: float
    largest_loss_bars: float
    max_wins: int
    max_losses: int
    profit_factor: float
    total_profit: float
    total_loss: float

def from_arrays(
    timestamps: typing.Sequence[int],
    opens: typing.Sequence[float],
    highs: typing.Sequence[float],
    lows: typing.Sequence[float],
    closes: typing.Sequence[float],
    volumes: typing.Sequence[float],
    symbol: typing.Optional[str] = None,
    symbols: typing.Optional[typing.Sequence[str]] = None,
    extra: typing.Optional[typing.Mapping[str, typing.Sequence[float]]] = None,
) -> list[Bar]:
    r"""从数组批量创建 Bar 列表 (Python 优化用)."""
    ...
